//! `.env.example` generation code.
//!
//! This module generates the `env_example()` method that produces a template
//! `.env.example` file documenting all required environment variables.
//!
//! # Generated Methods
//!
//! - [`generate_env_example_impl`] - Generates:
//!   - `env_example()` - Returns full `.env.example` content with header
//!   - `env_example_entries()` - Returns entries only (for nested structs)
//!
//! # Output Format
//!
//! ```text
//! # Auto-generated by procenv
//!
//! # Database connection URL (required, type: String)
//! DATABASE_URL=
//!
//! # Server port (type: u16)
//! # PORT=8080
//!
//! # API key for external service (required, secret, type: String)
//! API_KEY=
//! ```
//!
//! # Entry Format
//!
//! Each entry includes:
//! - **Doc comment** - From field's `///` documentation
//! - **Metadata** - `(required, secret, type: T)` as applicable
//! - **Variable line**:
//!   - Required: `VAR_NAME=`
//!   - With default: `# VAR_NAME=default_value` (commented)
//!
//! # Nested Structs
//!
//! Flatten fields delegate to their nested type's `env_example_entries()`:
//!
//! ```rust,ignore
//! #[env(flatten)]
//! database: DatabaseConfig,
//! // Calls DatabaseConfig::env_example_entries() in the generated code
//! ```

use proc_macro2::TokenStream as QuoteStream;
use quote::quote;
use syn::{Generics, Ident};

use crate::field::FieldGenerator;

/// Generate the `env_example()` method for .env.example generation.
pub fn generate_env_example_impl(
    struct_name: &Ident,
    generics: &Generics,
    fields: &[Box<dyn FieldGenerator>],
) -> QuoteStream {
    let (impl_generics, type_generics, where_clause) = generics.split_for_impl();

    // Collect fragments for each field
    let mut fragments: Vec<QuoteStream> = Vec::new();

    for field in fields {
        if field.is_flatten() {
            // Flattened field - generate call to nested type
            let fragment = field.generate_example_fragment();
            fragments.push(quote! {
                parts.push(#fragment);
            });
        } else {
            // Regular field - format entries at compile time
            let entries = field.example_entries();
            for entry in entries {
                let formatted = entry.format();
                fragments.push(quote! {
                    parts.push(#formatted.to_string());
                });
            }
        }
    }

    quote! {
        impl #impl_generics #struct_name #type_generics #where_clause {
            /// Generate a .env.example file content.
            pub fn env_example() -> std::string::String {
                let mut parts: std::vec::Vec<std::string::String> = std::vec::Vec::new();

                // Header
                parts.push("# Auto-generated by procenv".to_string());
                parts.push("".to_string());

                // Entries (from this struct and any nested configs)
                parts.push(Self::env_example_entries());

                parts.join("\n")
            }

            /// Generate .env.example entries without header.
            pub fn env_example_entries() -> std::string::String {
                let mut parts: std::vec::Vec<std::string::String> = std::vec::Vec::new();

                #(#fragments)*

                parts.join("\n")
            }
        }
    }
}
